version: '3.1'

services:
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_DB: comics-db
        POSTGRES_USER: comics-admin
        POSTGRES_PASSWORD: comics-pwd
      ports:
        - 5432:5432
